### ISSUE TITLE
Any way to enable pen pressure?

### ISSUE THREAD

**Issue by theterriblestidea** [kmkzt/svg-drawing#225]
I have tried drawing with an Apple Pencil and Wacom tablet on this. Saw a comment about implementing it, so just wondering. Awesome code!

**Comment by kmkzt** [comment]
Thank you for your interest.

Currently, I cannot change the pen pressure well.
In the case of a pen that gradually becomes thinner in pseudo, it is implemented [here].(https://kmkzt.github.io/react-hooks-svgdrawing/)

[code](https://github.com/kmkzt/react-hooks-svgdrawing/blob/88517e702bae398569e7d78273c80aa43a651f0e/src/example/app.tsx)

In the next version, we will consider adding a method that enables pressure sensitivity using the API below.

https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/pressure

The following API is planned.

```js
// Example pressure handle event.
const onPressure = (pressure) => {
  if (pressure == 0) {
    // No pressure
    process_no_pressure(event);
  } 
  if (pressure == 1) {
    // Maximum pressure
     drawing.penWidth += 0.5
  }
  // Default 
  drawing.penWidth -= 1
}
// Initialize pressure event
const drawing = new SvgDrawing(el, { onPressure })

// Update pressure event
drawing.onPressure = onPressure

```
