### ISSUE TITLE
changeDelay no longer working in 3.0.0

### ISSUE THREAD

**Issue by deluca-mike** [kmkzt/svg-drawing#235]
Everything was working fine in the previous version, but since the update, specifically with the new React module, `changeDelay` doesn't seem have any effect.

**Comment by kmkzt** [comment]
Thank you for reporting.

I fixed it [here](https://github.com/kmkzt/svg-drawing/pull/236).
It will be released at @svg-drawing/react@v4.0.0-beta.4.
