### ISSUE TITLE
instance always null in 4.0.0-beta.3

### ISSUE THREAD

**Issue by deluca-mike** [kmkzt/svg-drawing#238]
```
const [divRef, draw] = useSvgDrawing(svgDrawOptions);
console.log(draw.instance); // logs null, on every render
```

Followed the `react` example and not able to get a non-null instance from the draw object, while the rest of the properties are working/there.

**Comment by kmkzt** [comment]
@deluca-mike 
Thank you for reporting.
Is there a reproduction code?

I verified it as below and it seems to work.
https://github.com/kmkzt/svg-drawing/commit/b8efd5454b0278d0b520933f7aec0127a39fb3b9

<img width="333" alt="instance is null?" src="https://user-images.githubusercontent.com/30266990/87753576-d9bfb000-c83d-11ea-8159-90ba7d795263.png">

**Comment by kmkzt** [comment]
Sorry. It's hard to understand the example.
I updated the document of [`@svg-drawing/react`](https://github.com/kmkzt/svg-drawing/tree/master/packages/react#readme)
