### ISSUE TITLE
Functionality to import paths

### ISSUE THREAD

**Issue by deluca-mike** [kmkzt/svg-drawing#240]
Is there any interest in functionality to import `<path>` strings, and differentiate them between `drawn` and `imported`?

I am using this for another project and needed this functionality, so I am wondering if you'd like me to make a PR from my fork.

**Comment by kmkzt** [comment]
Thank you.
I'm interested. I would like to ask you to create a PR.

How do you use it?

**Comment by deluca-mike** [comment]
Basically, for my project, I need each `path` in the `svg` to have an `id` (uuidv4 for example) and a way for me to distinguish between paths that the user drew versus paths that were imported. Thus, I also assign each `path` element a `class`. I am still debating this `class` mechanism, as there are other ways of achieving what I want to do.

Also, because of the `id` being a randomly generated uuid, many of the unit tests fail. I don't have the time yet to make a proper PR that fixes all these unit test (or mocks the uuid generation), and I am still tinkering with how to differentiate between darn vs imported paths, if at all.

**Comment by kmkzt** [comment]
@deluca-mike 
This is a suggestion.
Can you solve the import part by using the character string/element parse function?

```js
const draw = new SvgDrawing(el)
const pEl = document.getElementById('importPath')
const path = new Path().parsePathElement(pEl)
// Or the new feature `parsePathString`. I haven't made it yet
// const path = new Path().parsePathString('<path d=" ... ></path>')

path.attrs.id = uuid()
path.attrs.class = 'importPath'
draw.addPath(path)
```

And how about assigning an identification number to the svg drawn as below at the required timing?

```js
draw.paths.map(p => {
  if (p.attrs.id) p.attrs.id = uuid()
  if (p.attrs.class) p.attrs.class = 'drawingPath'
})
```
Regarding identifier of path element, I solved it by creating an identifier at the necessary timing.

https://github.com/kmkzt/svg-drawing/blob/71729e6bc8a778f757a4ba2613cd604572daeb27/packages/animation/src/animation.ts#L221-L226

**Comment by deluca-mike** [comment]
I'll PR something now, but keep in mind it should not be merged due to failing tests

**Comment by kmkzt** [comment]
I will close this problem because it seems to be solved by using the method called parsePathElement.
