### ISSUE TITLE
Functionality to skeletonize images

### ISSUE THREAD

**Issue by theterriblestidea** [kmkzt/svg-drawing#261]
Since this library is getting an image-tracing feature, is there interest in skeletonizing images of lines as SVG paths? [example](https://media-exp1.licdn.com/dms/image/C4D22AQENyYj-bIHQKw/feedshare-shrink_1280/0?e=1599091200&v=beta&t=ZZkjtpMaV3ewXAP4Ql8dqS12huGLyF69ZYjM_VWFjow) + [demo](https://freeblet.com/)

(I used an implementation of the Guo-Hall thinning algorithm in Python, writing a JS port may be difficult.)

**Comment by kmkzt** [comment]
@theterriblestidea 
Thank you.

Great demo! I'm very interested.
It looks like line extraction is working fine.

I know about the Guo-Hall thinning algorithm for the first time.
I want to look it up when I have time. Please tell me if there is a link that gives an overview etc.

Since I referred to [imagetracerjs](https://github.com/jankovicsandras/imagetracerjs), I do not understand much about this library algorithm.

**Comment by theterriblestidea** [comment]
- [thinning algorithm examples](https://sites.google.com/site/rameyarnaud/research/c/voronoi)
- [better explained](https://web.archive.org/web/20160314104646/http://opencv-code.com/quick-tips/implementation-of-guo-hall-thinning-algorithm/)

I don't understand much either since I referred to [thinning_py3](https://pypi.org/project/thinning_py3/) [source code](https://github.com/tastyminerals/thinning_py3). Also after thinning the points have to be organized via [connected component labelling](https://en.wikipedia.org/wiki/Connected-component_labeling)

**Comment by jankovicsandras** [comment]
Hi,

imagetracerjs generates only SVG path elements. If you need shape outlines (but not topological skeletons), you can just disable the color fill at [line 1012](https://github.com/jankovicsandras/imagetracerjs/blob/a136ae5817cbe6171ae2822114ab4e55dc4c93b6/imagetracer_v1.2.6.js#L1012) , for example change it to this
```
return 'fill="transparent" stroke= ...
```

If you need to process geometry, take a look at this [tracedata processing example](https://github.com/jankovicsandras/imagetracerjs/blob/master/simplify_interop.html) .

**Comment by kmkzt** [comment]
@jankovicsandras 
I'm sorry to reply late. And thank you for pointing out.
If it make this change, it looks like outline.

In the case of characters, it seems better to use the topological skeleton.
